esphome:
  name: esphome-web-df88a5
  friendly_name: Motion Sensor

esp8266:
  board: nodemcuv2

# disable logging over serial port to free up UART
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: #####

uart:
  id: uart_1
  rx_pin: GPIO13  #D7
  tx_pin: GPIO15  #D8
  baud_rate: 256000
  data_bits: 8
  stop_bits: 1
  parity: NONE

ld2410:
  uart_id: uart_1
  timeout: 5s
  max_move_distance : 1.5m
  max_still_distance: 0.75m
  g0_move_threshold: 75
  g0_still_threshold: 85
  g1_move_threshold: 80
  g1_still_threshold: 90
  g2_move_threshold: 85
  g2_still_threshold: 95

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      filters:
        # delayed_off prevents false negatives
        - delayed_off: 10s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
  ssid: "Esphome-Web-Df88A5"
  password: "ZWLlH7FLNzvX"
